# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Mon Dec 01 18:42:28 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1205, 693)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tablefrequency = QtGui.QTableWidget(self.page)
        self.tablefrequency.setAutoFillBackground(False)
        self.tablefrequency.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tablefrequency.setFrameShadow(QtGui.QFrame.Sunken)
        self.tablefrequency.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tablefrequency.setDragDropOverwriteMode(True)
        self.tablefrequency.setAlternatingRowColors(False)
        self.tablefrequency.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tablefrequency.setCornerButtonEnabled(True)
        self.tablefrequency.setRowCount(0)
        self.tablefrequency.setObjectName(_fromUtf8("tablefrequency"))
        self.tablefrequency.setColumnCount(4)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablefrequency.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablefrequency.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablefrequency.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tablefrequency.setHorizontalHeaderItem(3, item)
        self.tablefrequency.horizontalHeader().setVisible(True)
        self.tablefrequency.horizontalHeader().setCascadingSectionResizes(False)
        self.tablefrequency.horizontalHeader().setDefaultSectionSize(222)
        self.tablefrequency.horizontalHeader().setHighlightSections(True)
        self.tablefrequency.horizontalHeader().setMinimumSectionSize(27)
        self.tablefrequency.horizontalHeader().setSortIndicatorShown(False)
        self.tablefrequency.horizontalHeader().setStretchLastSection(True)
        self.tablefrequency.verticalHeader().setVisible(False)
        self.tablefrequency.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.tablefrequency)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.graphsignal = Qwt5.QwtPlot(self.page_2)
        self.graphsignal.setObjectName(_fromUtf8("graphsignal"))
        self.verticalLayout_4.addWidget(self.graphsignal)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.formLayout_5 = QtGui.QFormLayout(self.dockWidgetContents)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.textserverip = QtGui.QLineEdit(self.dockWidgetContents)
        self.textserverip.setObjectName(_fromUtf8("textserverip"))
        self.horizontalLayout_4.addWidget(self.textserverip)
        self.formLayout_5.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.numserverport = QtGui.QSpinBox(self.dockWidgetContents)
        self.numserverport.setMinimum(1)
        self.numserverport.setMaximum(65535)
        self.numserverport.setProperty("value", 80)
        self.numserverport.setObjectName(_fromUtf8("numserverport"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.numserverport)
        self.formLayout_5.setLayout(1, QtGui.QFormLayout.SpanningRole, self.formLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnconnect = QtGui.QPushButton(self.dockWidgetContents)
        self.btnconnect.setObjectName(_fromUtf8("btnconnect"))
        self.horizontalLayout_6.addWidget(self.btnconnect)
        self.btndisconnect = QtGui.QPushButton(self.dockWidgetContents)
        self.btndisconnect.setObjectName(_fromUtf8("btndisconnect"))
        self.horizontalLayout_6.addWidget(self.btndisconnect)
        self.formLayout_5.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label = QtGui.QLabel(self.dockWidgetContents_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cboxviselect = QtGui.QComboBox(self.dockWidgetContents_2)
        self.cboxviselect.setObjectName(_fromUtf8("cboxviselect"))
        self.cboxviselect.addItem(_fromUtf8(""))
        self.cboxviselect.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboxviselect)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.dockWidgetContents_2)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.formLayout = QtGui.QFormLayout(self.page_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.checkboxfreqreq = QtGui.QCheckBox(self.page_3)
        self.checkboxfreqreq.setObjectName(_fromUtf8("checkboxfreqreq"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkboxfreqreq)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_interval = QtGui.QLabel(self.page_3)
        self.label_interval.setObjectName(_fromUtf8("label_interval"))
        self.horizontalLayout_5.addWidget(self.label_interval)
        self.dintervalsamples = QtGui.QDoubleSpinBox(self.page_3)
        self.dintervalsamples.setDecimals(3)
        self.dintervalsamples.setMinimum(0.001)
        self.dintervalsamples.setMaximum(1000000000.0)
        self.dintervalsamples.setSingleStep(0.1)
        self.dintervalsamples.setProperty("value", 0.2)
        self.dintervalsamples.setObjectName(_fromUtf8("dintervalsamples"))
        self.horizontalLayout_5.addWidget(self.dintervalsamples)
        self.formLayout.setLayout(5, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_samples = QtGui.QLabel(self.page_3)
        self.label_samples.setObjectName(_fromUtf8("label_samples"))
        self.horizontalLayout.addWidget(self.label_samples)
        self.numsamples = QtGui.QSpinBox(self.page_3)
        self.numsamples.setMinimum(2)
        self.numsamples.setMaximum(100000000)
        self.numsamples.setProperty("value", 10)
        self.numsamples.setObjectName(_fromUtf8("numsamples"))
        self.horizontalLayout.addWidget(self.numsamples)
        self.formLayout.setLayout(4, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.btnconfigfm = QtGui.QPushButton(self.page_3)
        self.btnconfigfm.setObjectName(_fromUtf8("btnconfigfm"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.btnconfigfm)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.page_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cboxaveragetype = QtGui.QComboBox(self.page_3)
        self.cboxaveragetype.setObjectName(_fromUtf8("cboxaveragetype"))
        self.cboxaveragetype.addItem(_fromUtf8(""))
        self.cboxaveragetype.addItem(_fromUtf8(""))
        self.cboxaveragetype.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cboxaveragetype)
        self.formLayout.setLayout(1, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.page_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.numaveragenodes = QtGui.QSpinBox(self.page_3)
        self.numaveragenodes.setMinimum(1)
        self.numaveragenodes.setMaximum(4000)
        self.numaveragenodes.setProperty("value", 20)
        self.numaveragenodes.setObjectName(_fromUtf8("numaveragenodes"))
        self.horizontalLayout_2.addWidget(self.numaveragenodes)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.btnfreqrequest = QtGui.QPushButton(self.page_3)
        self.btnfreqrequest.setObjectName(_fromUtf8("btnfreqrequest"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.btnfreqrequest)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.page_4)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.page_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.cboxsignaltype = QtGui.QComboBox(self.page_4)
        self.cboxsignaltype.setObjectName(_fromUtf8("cboxsignaltype"))
        self.cboxsignaltype.addItem(_fromUtf8(""))
        self.cboxsignaltype.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cboxsignaltype)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.page_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.dnumfrequency = QtGui.QDoubleSpinBox(self.page_4)
        self.dnumfrequency.setMaximum(100000000.0)
        self.dnumfrequency.setProperty("value", 5000.0)
        self.dnumfrequency.setObjectName(_fromUtf8("dnumfrequency"))
        self.horizontalLayout_8.addWidget(self.dnumfrequency)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labeldutycycle = QtGui.QLabel(self.page_4)
        self.labeldutycycle.setObjectName(_fromUtf8("labeldutycycle"))
        self.horizontalLayout_9.addWidget(self.labeldutycycle)
        self.numdutycycle = QtGui.QSpinBox(self.page_4)
        self.numdutycycle.setMinimum(0)
        self.numdutycycle.setMaximum(100)
        self.numdutycycle.setProperty("value", 50)
        self.numdutycycle.setObjectName(_fromUtf8("numdutycycle"))
        self.horizontalLayout_9.addWidget(self.numdutycycle)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.btnconfigfg = QtGui.QPushButton(self.page_4)
        self.btnconfigfg.setObjectName(_fromUtf8("btnconfigfg"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.btnconfigfg)
        self.stackedWidget_2.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_3.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setObjectName(_fromUtf8("dockWidget_3"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.textbrowser = QtGui.QTextBrowser(self.dockWidgetContents_3)
        self.textbrowser.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textbrowser.setFrameShadow(QtGui.QFrame.Sunken)
        self.textbrowser.setLineWidth(1)
        self.textbrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textbrowser.setObjectName(_fromUtf8("textbrowser"))
        self.horizontalLayout_10.addWidget(self.textbrowser)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_3)
        self.menufileloadsignal = QtGui.QAction(MainWindow)
        self.menufileloadsignal.setObjectName(_fromUtf8("menufileloadsignal"))
        self.menufilesavetable = QtGui.QAction(MainWindow)
        self.menufilesavetable.setObjectName(_fromUtf8("menufilesavetable"))
        self.menufilecleartable = QtGui.QAction(MainWindow)
        self.menufilecleartable.setObjectName(_fromUtf8("menufilecleartable"))
        self.menu_File.addAction(self.menufileloadsignal)
        self.menu_File.addAction(self.menufilesavetable)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.menufilecleartable)
        self.menubar.addAction(self.menu_File.menuAction())
        self.label_4.setBuddy(self.textserverip)
        self.label_5.setBuddy(self.numserverport)
        self.label.setBuddy(self.cboxviselect)
        self.label_3.setBuddy(self.cboxaveragetype)
        self.label_2.setBuddy(self.numaveragenodes)
        self.label_6.setBuddy(self.cboxsignaltype)
        self.label_7.setBuddy(self.dnumfrequency)
        self.labeldutycycle.setBuddy(self.numdutycycle)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.cboxviselect, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget_2.setCurrentIndex)
        QtCore.QObject.connect(self.stackedWidget_2, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.cboxviselect.setCurrentIndex)
        QtCore.QObject.connect(self.stackedWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), self.cboxviselect.setCurrentIndex)
        QtCore.QObject.connect(self.cboxviselect, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textserverip, self.numserverport)
        MainWindow.setTabOrder(self.numserverport, self.btnconnect)
        MainWindow.setTabOrder(self.btnconnect, self.btndisconnect)
        MainWindow.setTabOrder(self.btndisconnect, self.cboxviselect)
        MainWindow.setTabOrder(self.cboxviselect, self.numaveragenodes)
        MainWindow.setTabOrder(self.numaveragenodes, self.cboxaveragetype)
        MainWindow.setTabOrder(self.cboxaveragetype, self.btnconfigfm)
        MainWindow.setTabOrder(self.btnconfigfm, self.btnfreqrequest)
        MainWindow.setTabOrder(self.btnfreqrequest, self.cboxsignaltype)
        MainWindow.setTabOrder(self.cboxsignaltype, self.dnumfrequency)
        MainWindow.setTabOrder(self.dnumfrequency, self.numdutycycle)
        MainWindow.setTabOrder(self.numdutycycle, self.btnconfigfg)
        MainWindow.setTabOrder(self.btnconfigfg, self.tablefrequency)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Virtual Instrument", None))
        item = self.tablefrequency.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sample", None))
        item = self.tablefrequency.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Frequency (Hz)", None))
        item = self.tablefrequency.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date (dd/mm/yy)", None))
        item = self.tablefrequency.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Connection", None))
        self.label_4.setText(_translate("MainWindow", "UDP Server IP:", None))
        self.textserverip.setText(_translate("MainWindow", "172.19.5.91", None))
        self.label_5.setText(_translate("MainWindow", "UDP Server Port:", None))
        self.btnconnect.setText(_translate("MainWindow", "Connect", None))
        self.btndisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "Virtual Instrument", None))
        self.label.setText(_translate("MainWindow", "Instrument:", None))
        self.cboxviselect.setItemText(0, _translate("MainWindow", "Frequency Meter", None))
        self.cboxviselect.setItemText(1, _translate("MainWindow", "Function Generator", None))
        self.checkboxfreqreq.setText(_translate("MainWindow", "Auto Request", None))
        self.label_interval.setText(_translate("MainWindow", "Interval (seconds)", None))
        self.label_samples.setText(_translate("MainWindow", "Samples:", None))
        self.btnconfigfm.setText(_translate("MainWindow", "Configure Frequency Meter", None))
        self.label_3.setText(_translate("MainWindow", "Average Type:", None))
        self.cboxaveragetype.setItemText(0, _translate("MainWindow", "Simple", None))
        self.cboxaveragetype.setItemText(1, _translate("MainWindow", "Weighted", None))
        self.cboxaveragetype.setItemText(2, _translate("MainWindow", "Exponential", None))
        self.label_2.setText(_translate("MainWindow", "Average Nodes:", None))
        self.btnfreqrequest.setText(_translate("MainWindow", "Frequency Request", None))
        self.label_6.setText(_translate("MainWindow", "Signal Type:", None))
        self.cboxsignaltype.setItemText(0, _translate("MainWindow", "Square", None))
        self.cboxsignaltype.setItemText(1, _translate("MainWindow", "Non-Square", None))
        self.label_7.setText(_translate("MainWindow", "Frequency (Hz):", None))
        self.labeldutycycle.setText(_translate("MainWindow", "Duty Cycle (%):", None))
        self.btnconfigfg.setText(_translate("MainWindow", "Configure Function Generator", None))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "Error/Warning/Info", None))
        self.menufileloadsignal.setText(_translate("MainWindow", "Load signal", None))
        self.menufilesavetable.setText(_translate("MainWindow", "Save Table", None))
        self.menufilecleartable.setText(_translate("MainWindow", "Clear Table", None))

from PyQt4 import Qwt5
